[package]
name = "zopra_macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for Zopra"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ppmpreetham/zopra"
readme = "README.md"
keywords = ["ui", "gpui", "macros", "declarative"]
categories = ["development-tools::procedural-macro", "gui"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full", "visit-mut", "extra-traits"] }
